esphome:
  name: office-motion

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "19311feb9ee8f4f784e10905bf0216a3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-Motion Fallback Hotspot"
    password: "y6ZIZM4AmNlE"

captive_portal:

binary_sensor:
  - platform: gpio
    pin: D7
    name: "Office motion"
    device_class: motion

sensor:
  - platform: adc
    pin: A0
    name: "Office Light"
    unit_of_measurement: lux
    filters:
      - lambda: return (x / 10000.0) * 2000000.0;